### PR TITLE
added R:(Arcane Trickster), updated F:(Eldritch Knight)

### PR DESCRIPTION
**Pull request by afluffygrue**
used CSV file to filter Wizard Enchant and Illusion to add Rogue (Arcane Trickster)
used CSV file to filter Wizard Cantrips to add Rogue (Arcane Trickster) and Fighter (Eldritch Knight)
Fighter (Eldritch Knight) was missing from some Wizard Cantrips when all should be available (see PHB pg75)
*bonus fun fact - spell check thinks "Eldritch" should be "britches"

### CODE REVIEW

**Comment by ceryliae** [comment]
Great, thanks.

**Comment by Phied** [comment]
Crap.  No it wasn't all available wizard spells.  It was only 2 spell types with the option at special levels

**Comment by afluffygrue** [comment]
All Cantrips, and only two schools for the 1-9 spells

**Comment by Phied** [comment]
I misread that you did say cantrop!  My bad lol

**Pull request merged**
