### PR TITLE
Update DM Bestiary.xml

### PR DESCRIPTION
**Pull request by Turelim**
Corrections and rolls added from MM pg. 12 - 78 (From Aarakocra to all Devils)

### CODE REVIEW

**Comment by Turelim** [comment]
Delete the branch, Idk what the hell happened here... I didn't see the mess, i will upload the changes in a new pull. My GitHub is crazy, seems like it uploaded a completely new version instead of just updating my changes.

**Comment by ceryliae** [comment]
Alright, I fixed the damage that was done, but this had been sitting on the dropbox for 5 hours. Nobody told me they had any problems importing the DM Bestiary, so I guess nobody tried to import it during that time.

Things that happened with your pull:

36k lines of code got added. The correct version of the bestiary file is roughly 18k lines, so it seems like somehow you added another version to it, like your changes were just added on instead of replacing anything. That was a GitHub screw up. However, your version also introduced two problems. 

First, you cannot add an attack tag to a trait, it breaks the import. 

Second, you had quite a few unclosed attack tags. For example, with the Aarakocra, this is what you had. You forgot the / to close the attack tag.

```
     <action>

        <name>Talon</name>

        <text>Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 4 (ld4 + 2) slashing damage.</text>

        <attack>Talon|4|1d4+2<Attack>

    </action>
```

Everyone makes mistakes, but before you submit a pull, make sure you try to import it into the app.

**Comment by ceryliae** [comment]
Looks like you CAN have `<attack>` tags in traits, but only for the Player bestiary right now. I'm not sure how you want to proceed with updating the monsters, because we have no ETA on when the DM app will be updated to include things like this.

**Comment by Turelim** [comment]
Pardon me, I will fix my errors in a new pull

**Comment by Turelim** [comment]
Well, I added them because it was supposed to be supported (that what DM app says about attack tag), we can request the creator to add them in the app or include a general "roll" tag for thing that don't belong to an attack.

**Comment by Turelim** [comment]
I just forget it... Can you remove the extra file in the bestiary? I will add my changes in a new pull.

**Comment by ceryliae** [comment]
Sync up with the current version, I fixed the issues that were preventing the file from being successfully imported.

Regarding attack tags, they partially work in the DM app right now. They don't seem to show up in the compendium, but they do show up in encounters. Since they don't break the file and have some functionality, there's no reason not to include them.

**Comment by ceryliae** [comment]
Will do.

**Comment by ceryliae** [comment]
Do you have a google account? If you do, send me an email so that I can talk to you through google hangout chat, instead of here.

**Comment by Turelim** [comment]
sure, I have one :)
I don't know how to send private messages in GitHub but i will put here meanwhile you send me a message, after that i will delete this response.
turel.grodriguez@gmail.com

**Comment by ceryliae** [comment]
I sent you a message

**Pull request merged**
