### PR TITLE
Patch 17

### PR DESCRIPTION
**Pull request by ttbakiatwoam**

### CODE REVIEW

**Comment by Phied** [comment]
Do you think release date or alphabetical would work better?  I am not sure on which would be better.

**Comment by ttbakiatwoam** [comment]
I personally Like release date that way the new stuff (stuff we should be working on) is last.

**Comment by ttbakiatwoam** [comment]
It also makes leveling information easier.

**Comment by Phied** [comment]
That works for me.

**Comment by Phied** [comment]
I'll sync it up when I get home then if cerylaie doesn't sync it before then

**Comment by ttbakiatwoam** [comment]
Sounds good, I am still trying to help Lore with his pull request. But I may just put that stuff up my self tonight.

**Pull request merged**
