### PR TITLE
Fix spelling errors and minor missing text in spells and classes.  Add DMG Item Rarity

### PR DESCRIPTION
**Pull request by vagueGM**

### CODE REVIEW

**Comment by vagueGM** [comment]
I do not use the GM5 or Fight Club apps, so I do not know if they allow free-form fields or if they have a schema.
I would have liked to add the item rarity as a <rarity> element, but for now it is just another text element similar to the source text elements for page numbers.

**Comment by vagueGM** [comment]
I have been adding more changes and this pull request is getting rather scattered across files and change types, if you would prefer separate PRs for each of them I can resubmit.

**Comment by ceryliae** [comment]
Hey,

Thanks for all the work you've done!

No, I'll just merge this one. Do you have anything else you're working on? If you do, I'll wait before I update the Dropbox.

**Comment by vagueGM** [comment]
I would **not** hold off on updating the Dropbox, there is no telling when I will get round to doing more updating.
Future plans are: adding the item rarities for the other books (but I do not have them), adding Monster Manual page references, and maybe some formatting and cleanup of bullets.

I **might** look at doing the MM reference this weekend, if time permits.

**Comment by ceryliae** [comment]
Fighting club doesn't let you add extra fields. And copy that.

**Comment by vagueGM** [comment]
I am looking at adding the MM page references, but am not sure where to put them.
The obvious place - given the current data shape - is in the <type> tag, but that might be used by the Fighting Club app for sorting, and making each entry unique (due to page numbers) might be an issue.
If the commas in the type tag serve as delimiters to the app then I can change `<type>humanoid (aarakocra), monster manual</type>` to something like `<type>humanoid (aarakocra), monster manual, MMpg12</type>`

`MMpg12` could also be `MM12,` or `pg12,` or even `pg.12`.

If that field is just freeform text or a subheading them I can make it be `<type>humanoid (aarakocra), monster manual page 12</type>`

Any thoughts on the format?

**Pull request merged**
