### PR TITLE
Some more formatting

### PR DESCRIPTION
**Pull request by daemitus**

### CODE REVIEW

**Comment by daemitus** [comment]
Per the tag reordering:
This allows me (with the current setup I'm using) to properly import and
export the xml so I can diff the files and programatically identify
inconsistencies.

This also ensures that the template is applied consistently across all
items.

**Comment by ceryliae** [comment]
How many more of these do you have? Ideally I'd like to do all of these fixes at once on the dropbox

**Comment by daemitus** [comment]
What I'm doing is goofing around with making an android app that is compatible with these xml files you've lovingly put together. Spells and Items are done. Working on the bestiary next. Character Files (except for classes) are also done.

**Comment by ceryliae** [comment]
Alright, well be warned not to include the files in the app by default. Leo used to do that with the Lions Den apps but he got a DMCA takedown from WotC, which led to the way the app works right now (which is actually a lot better than what the app was before)

**Pull request merged**
