### PR TITLE
Fix two dice rolls

### PR DESCRIPTION
**Pull request by 153957**
`dl0` -> `d10`

Where should changes for the DM screen be proposed, here or at ceryliae/5edmscreen, or both?

### CODE REVIEW

**Comment by ceryliae** [comment]
These sort of changes should go over at 5edmscreeen. 

The version here is intended for importing into the iOS app and I'm keeping JavaScript out of that version. 

Also, the version over here is basically the mobile version over at 5edmscreen. 

Finally, I'm doing a rewrite of the code right now. Cleaning code up, formatting it so it can be easily updated in the future. So while I do appreciate the contribution, I won't be able to merge any of them until after I finish the rewrite. I've been traveling m right now and I've been working on it on the plane. I get home on February 6th and then I'll start syncing my changes.

**Comment by ceryliae** [comment]
Wait, I misunderstood what these changes were. Never mind basically my entire other comment.

**Comment by 153957** [comment]
So my question stands, this change should also be merged into 5edmscreen, the same typo exists there. How will they be kept in sync?

**Comment by ceryliae** [comment]
Go ahead and do this change for the mobile screen over on the other repo,
and I've gone ahead and fixed it on my working copy for the website
version.

**Comment by ceryliae** [comment]
I'm getting on a plane so I'll be out of touch for a while

**Pull request merged**
