### PR TITLE
fixed tabbing

### PR DESCRIPTION
**Pull request by LoreMasterRoth**
Tabbing is fixed. Still can't figure out how to undo the commits from earlier today. I know they're made to un-synced files. Would like to remove them. Don't know how.

### CODE REVIEW

**Comment by ttbakiatwoam** [comment]
Sync your fork first then make your changes then request a pull.

**Comment by LoreMasterRoth** [comment]
I'm working off the browser and I have no idea how to do that.

**Comment by Phied** [comment]
Here, read this.  Maybe it will help.

https://help.github.com/articles/creating-a-pull-request/

**Comment by ttbakiatwoam** [comment]
There are some good YouTube videos for newbies.

**Comment by LoreMasterRoth** [comment]
Ok. I'll wait until I have time to do that. Do you want me to email you the
data for the RoT bestiary so no one has to redo it?

On Sat, Apr 4, 2015 at 10:41 PM, Andrew Saunders notifications@github.com
wrote:

> There are some good YouTube videos for newbies.
> 
> Sent from my iPhone
> 
> > On Apr 4, 2015, at 20:40, Phied notifications@github.com wrote:
> > 
> > Here, read this. Maybe it will help.
> > 
> > https://help.github.com/articles/creating-a-pull-request/
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ceryliae/DnDAppFiles/pull/45#issuecomment-89707232.

## 

Adam M. Roth
adam.roth.cg@gmail.com

**Comment by Phied** [comment]
I can see that the changes will not be able to be merged automatically.  You may want to email the files you changed to @ceryliae .  At that point, Ceryliae can probably put them in manually.  It is possible to merge them manually via the command line, but honestly, it'll probably be easier just emailing what you did change.

**Comment by LoreMasterRoth** [comment]
I am definitely in over my head on this, I'll pop back in as soon as I have
a better grasp of the interface. If anyone is so inclined the data for the
Rise of Tiamat is at:

https://www.dropbox.com/s/n41tlx6dsupiy2o/Rise%20of%20Tiamat%20Bestiary2.xml?dl=0

On Sat, Apr 4, 2015 at 10:45 PM, Adam Roth adam.roth.cg@gmail.com wrote:

> Ok. I'll wait until I have time to do that. Do you want me to email you
> the data for the RoT bestiary so no one has to redo it?
> 
> On Sat, Apr 4, 2015 at 10:41 PM, Andrew Saunders <notifications@github.com
> 
> > wrote:
> > 
> > There are some good YouTube videos for newbies.
> > 
> > Sent from my iPhone
> > 
> > > On Apr 4, 2015, at 20:40, Phied notifications@github.com wrote:
> > > 
> > > Here, read this. Maybe it will help.
> > > 
> > > https://help.github.com/articles/creating-a-pull-request/
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/ceryliae/DnDAppFiles/pull/45#issuecomment-89707232.
> 
> ## 
> 
> Adam M. Roth
> adam.roth.cg@gmail.com

## 

Adam M. Roth
adam.roth.cg@gmail.com

**Comment by Phied** [comment]
@LoreMasterRoth don't worry to much.  We will get that data put up there.  I'm sure @ceryliae will grab it tonight or in the morning and get it set up for you.  It takes a little while to get used to the Github, but once you do, it's not to bad.

**Comment by ttbakiatwoam** [comment]
I'll get it up and set to pull when I get home.

**Comment by ceryliae** [comment]
Set up another pull request

**Comment by ttbakiatwoam** [comment]
I reviewed the file and there are several differences between the standard and the file's current configuration. I made some initial corrections and asked Lord to correct his file to the standard. Using Lord's work, I should have a file up to spec available in a little bit I just have to double check all the monsters. For instance he recreated the Dragonwing and Dragonclaw despite them already being done... So, I decided to review them all to double check they match the books.

**Pull request closed without merging**
