### PR TITLE
Rise of Tiamat Bestiary

### PR DESCRIPTION
**Pull request by LoreMasterRoth**
I've completed these entries.

### CODE REVIEW

**Comment by LoreMasterRoth** [comment]
Sorry again. I was just trying to make a pull request for the new bestiary. Still learning the ins and outs here.

**Comment by ttbakiatwoam** [comment]
please go back through your updates and correct your spacing/tabbing. Also you didn't pull the most recent items files... I added 0s to the weights and corrected some couple typos.

**Comment by LoreMasterRoth** [comment]
This pull request is all jacked up, so I'm a bit confused to what you're referring. This was only supposed to be the Rise of Tiamat bestiary only. The other file changes were old and I didn't want to include them, so you can reject those. 

If the spacing/tabbing is an issue in the Tiamat file, what's the style guide? I want to fix it.

**Comment by ttbakiatwoam** [comment]
Just close the request at the bottom next to commit... 

Look at the HotDQ Bestiary for the proper tabbing.

**Comment by LoreMasterRoth** [comment]
I've fixed the tabbing. How do I remove commits on my fork from earlier
today? If I give a pull request it will send all the unsynced files again.

On Sat, Apr 4, 2015 at 9:38 PM, Andrew Saunders notifications@github.com
wrote:

> Just close the request at the bottom next to commit...
> 
> Look at the HotDQ Bestiary for the proper tabbing.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ceryliae/DnDAppFiles/pull/44#issuecomment-89699410.

## 

Adam M. Roth
adam.roth.cg@gmail.com

**Pull request closed without merging**
