### PR TITLE
Various updates

### PR DESCRIPTION
**Pull request by 153957**
For consistency replaced all `<text> </text>` by `<text />`.
Fixed a sentence in the README.
Fixed a missing opening bracket in the Templates.
Update the Compendiums using the new script.

### CODE REVIEW

**Comment by afluffygrue** [comment]
I remember doing the <text></text> intentionally because <text /> didn't do what I wanted, but I can't recall what that was. 

Thanks,
Dan

Typed with my thumbs.

**Comment by 153957** [comment]
This comment was written in some of the files:

`Due to a bug in D20 Fight Club app importing, "<text/>" has been replaced with "<text> </text>" for line breaks`

These empty text tags are used for blank lines. There were already some `<text />` tags in the Compendium files and those looked fine in the DM app, I did not check in Fight Club yet..

**Comment by ceryliae** [comment]
Can you check these files to see if <text /> works before I merge this
request?

I think the bug has been fixed by now, but I don't know.

**Comment by 153957** [comment]
I just installed Fight Club and it looks fine too.

**Pull request merged**
