### PR TITLE
DandWiki Homebrew items

### PR DESCRIPTION
**Pull request by Lee62me**
this is a work in progress. I plan on adding all of the homebrew races, classes, items, etc. from dandwiki.com so that it can be used in fight club 5

### CODE REVIEW

**Comment by Lee62me** [comment]
this is a work in progress. I plan on adding all of the homebrew races, classes, items, etc. from dandwiki.com so that it can be used in fight club 5

**Comment by Lee62me** [comment]
I am working on adding all of the Homebrew items that I have found in [dandwiki.com](https://www.dandwiki.com/wiki/5e_Homebrewl) and making it so that it can be used in Fight Club 5. I would appreciate any help along the way. There are about 9,910 items that I need to add. They are races, classes, items, backgrounds, etc., so i have a long way to go

**Comment by Lee62me** [comment]
I also figured out that you can add race/class descriptions as traits or features for those who want to know what they are and what they can do, as well as provide a background to build from for their characters

**Comment by Lee62me** [comment]
Would it be possible for someone to go over my code? Every time I try to add it to the app, it keeps on telling me that there is something wrong.

**Comment by jplcny** [comment]
I will have time tomorrow evening to look it over if someone else doesn’t get to it before then.

Jamie

**Comment by Lee62me** [comment]
thanks, if you want to, could you maybe help me transcribe all of the 5th edition homebrew items from dandwiki.com? There are about 10000 different items to code

**Comment by santiagoShaggyShamrock** [comment]
Hi, do you have a template to create a class in XML, I want to make a Chronomancer and some other stuff.

**Comment by joshuaedwardk** [comment]
Let me look, I moved onto other projects, it won’t be until Monday at the earliest.

**Comment by santiagoShaggyShamrock** [comment]
No problem, thanks!! Whenever you have time, I want to make a Red Mage,
Samurai, Chronomancer and Ninja classes with respective spells for me and
my group so whenever you have a free time.

I have the PDF for these classes if you want/need them.

Take care.

**Pull request closed without merging**
