### PR TITLE
Update Out of the Abyss.xml

### PR DESCRIPTION
**Pull request by atiupin**

### CODE REVIEW

**Comment by ceryliae** [comment]
Apparently I can't spell. Thanks.

**Comment by ceryliae** [comment]
Could you also fix this in the relevant compendium files please.

**Comment by atiupin** [comment]
Should I always do this? Aren't they auto-generated?

**Comment by ceryliae** [comment]
No, I don't know how to do that, if you know how to do that, it would be
great.

**Comment by atiupin** [comment]
I'll try to do something with it.

**Pull request merged**
